#!/usr/bin/env bash
# Bash script to start and configure an nginx server
sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
