#!/usr/bin/env bash
# Infinite process.

# Function to handle SIGTERM and SIGQUIT signals
cleanup() {
  rm -f /var/run/myscript.pid
  exit 0
}

# Function to handle SIGINT signal
handle_sigint() {
  echo "Y U no love me?!"
}

handle_sigterm() {
  echo "I hate the kill command"
  cleanup
}
# Register the function to be called on SIGTERM and SIGQUIT and SIGINT
trap 'cleanup' SIGQUIT
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT

# Get the PID of this script
echo $$ > /var/run/myscript.pid

while true; do
  echo "To infinity and beyond"
done

