#!/usr/bin/env bash
# Bash (init) script that manages {manage_my_process}. 
stop_process() {
	rm -f /var/run/my_process.pid
	pkill -f manage_my_process > /dev/null 2>&1
}

start_process() {
	./manage_my_process &
	pgrep -fo manage_my_process > /var/run/my_process.pid
}

case $1 in
	'start')
		echo "manage_my_process started"
		start_process
		;;
	'stop')
		echo "manage_my_process stopped"
		stop_process
		;;
	'restart')
		echo "manage_my_process restarted"
		stop_process
		start_process
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
