#!/usr/bin/env bash
# Displays lines containing the bash word, getting the PID of Bash process.
# shellcheck disable=SC2009
pids=$(pgrep -f "bash")

for pid in $pids; do
    process_name=$(ps -p "$pid" -o comm=)
    echo "$pid $process_name"
done
