#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while
# loop + IFS.

IFS=":"

while read -r u_name passwd uid gid u_info home shell; do
	echo "
	The user $u_name is part of the $gid gang, lives in $home and\nrides $shell.\n
	$uid's place is protected by the passcode $passwd, more info about the\n
	user here: $u_info\n
	"
done < /etc/passwd

unset IFS
