#!/usr/bin/env bash
# Diisplays Best School 10 times, but for the 9th iteration, displays
# Best School and then Hi on a new line.
x=1
while [ $x -le 10 ]; do
	if [ $x -ne 9 ]; then
		echo "Best school"
	else
		echo "Hi"
	fi
	x=$((x + 1))
done	
