#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
hour=0
mins=1
while [ $hour -le 12 ]; do
	echo  "Hour: $hour"
	while [ $mins -le 59 ]; do
		echo $mins
		mins=$((mins + 1))
	done
	mins=1
	hour=$((hour + 1))
done
